// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqvztkscyeezhocpvdtr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtxdnp0a3NjeWVlemhvY3B2ZHRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMjM3NDksImV4cCI6MjA2NDY5OTc0OX0._FAY6iUQdUEvIWbWPxj7njkapLlv_fEFqmBPqgUI6Ns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);